### ISSUE TITLE
No copy-paste from clipboard

### ISSUE THREAD

**Issue by bdenham** [devgpt-labs/devgpt-releases#107]
It seems that the app doesn't allow pasting from the clip-board. This makes it practically unusable.

**Comment by HRA42** [comment]
Hi @bdenham,

Thanks for your report. Could you please tell us a bit more:

- Version number installed
- Operating System

**Comment by timoogo** [comment]
i have the same issue
- **version number**: 1.1.1 
- **Operating System**: Windows 11 - 22H2
Also, we can't paste into the prompt some code / text

**Comment by alromano-q4** [comment]
I'm also getting this issue, I can't copy/paste anything into any prompt area.

- v 1.1.1
- macOS Ventura 13.5.2 (22G91)

**Comment by fabrizionastri** [comment]
me too

**Comment by timoogo** [comment]
> I encoutered the same issue (v1.1.1 on windows 11). After some trials and error, I found the cause.
> 
> It's because the prompt is limited to 350 characters (at least in the free version). If you want to paste more, it does not work - which is a major limitation (even for the free version). However, the fact that there is no feedback explaining why the paste does not work is more than a limitation - it's a UX issue.
> 
> My recommendations:
> 
>     * increase the prompt size (1500 should be a minimum, ChatGPT allows more 32k tokens (so ~16k words), so that gives plenty of room for other contextual information you need to pass on
> 
>     * allow unrestricted paste
> 
>     * provide helpful feedback if prompt size is exceeded so that the users can trim it if needed

Even in the paid version, it's the same issue.
If i try to copy "word", and i try to paste, it won't work...
