### ISSUE TITLE
``props.message.content returned falsey.`` 

### ISSUE THREAD

**Issue by hpsbe** [devgpt-labs/devgpt-releases#112]
this is what it showed me when I asked devgpt to find potential vulnerabilities on my solidity contract

**Comment by NayLin99** [comment]
This error also happened to me.
<img width="909" alt="image" src="https://github.com/february-labs/devgpt-releases/assets/24827948/c000e766-fed1-464b-a960-254911ddc5e8">

**Comment by HRA42** [comment]
Hi @hpsbe :)

In order to help us debug, we need the following information, be sure to hide any sensitive information when submitting the below:

- Prompt used:
- Error message received (or unexpected behaviour):
- Version number installed:
- Operating System:

**Comment by HRA42** [comment]
Hi @NayLin99,

In order to help us debug, we need the following information, be sure to hide any sensitive information when submitting the below:

Version number installed:
Operating System

**Comment by NayLin99** [comment]
> Hi @NayLin99,
> 
> In order to help us debug, we need the following information, be sure to hide any sensitive information when submitting the below:
> 
> Version number installed: Operating System

Version number installed: 1.1.1
Operating System: macOS Ventura Version 13.5.2 (22G91)

**Comment by jeanmenta** [comment]
Version 1.1.1
MacBook Pro M1. macOS Ventura 13.2.1 (22D68)

<img width="972" alt="Screenshot 2023-09-18 at 19 14 22" src="https://github.com/february-labs/devgpt-releases/assets/89556322/4febe2a2-0c80-4589-8c99-fa70088d6a0c">

**Comment by AvyonWar** [comment]
Version 1.1.1
Windows 11 Pro, Version: 22H2, Operating System :22621.2283


![Screenshot (760)](https://github.com/february-labs/devgpt-releases/assets/110771481/7abd3410-3ba9-4be1-a4ff-7438c623dab7)
