### ISSUE TITLE
moving files without asking

### ISSUE THREAD

**Issue by andrews-work** [devgpt-labs/devgpt-releases#117]
within my project folder I have a main directory with 4 sub directories: pages, scripts, images, css. After syncing devGPT suggestion to visual studio code all the files were moved from the subdirectories to the main directory, this was very annoying. 

As a suggestion, the AI should not move files or directories from their original location unless explicitly asked.

**Comment by ash-lewis** [comment]
Resolved in the v 2.0.1!
