### ISSUE TITLE
Some repositories are not showing.

### ISSUE THREAD

**Issue by TriLea** [devgpt-labs/devgpt-releases#125]
There seems to be a cutoff for repositories that is making it impossible for me to select my other works.

**Comment by fivaz** [comment]
same for me, my favorite repositories can't be selected

**Comment by jordanbmowry** [comment]
I am unable to find some of my repos in github

**Comment by HRA42** [comment]
Hi @fivaz @jordanbmowry @TriLea,

the Issue should be fixed by now.

If you still have issues with the app, please let us know and I will reopen the issue.
