### ISSUE TITLE
Task History and repo sync missing, emoticons dont indicate that they have been clicked

### ISSUE THREAD

**Issue by derickdsouza** [devgpt-labs/devgpt-releases#131]
Some feedback along with the issue
My first attempt at using the web version
I used my personal id and repository as I am testing the waters
I started with the same prompt I have tried for every release of DevGPT
To analyse a Vue component and to provide suggestions
I got excellent suggestions - far better than I got from any version prior to this! Great Job!
I could not find the sync to repo version
So I asked for the suggestions to be synced to my repo
DevGPT started a new task saying it cannot and gave me git cloning instructions etc.
I saw that I could no longer see the suggestions
Tried to look for history and could not locate it either.
I clicked on the feedback emoticons as well - but they don't seem to be doing anything (or not indicating anything)
Will continue to use it

**Comment by derickdsouza** [comment]
emoticons when clicked are responding wiht a tick that last 3 seconds - although it does not retain state, it atleast indicates that teh click was registered which is good enough for me as a user. I tried adding unit tests for my component - got very good results - however with every follow up prompt it is losing the responses from the previosu prompts which make sit less useful and a bit tedious as I would have ot keep copying out the text and break my flow of thought. It did retain context though across prompts.  Also noted that the @filename did not show any suggestions as it did a couple of days ago - it did pick up the right file though.

**Comment by HRA42** [comment]
Hi @derickdsouza :)

Do you use the desktop app or the web app?

**Comment by derick-dsouza** [comment]
This was feedback from my first use of the web version after having used the desktop version earlier. The Emoticons have been fixed. The web version (as of now) does not have a task history - each prompt requires me to copy the output before I can make a follow up prompt. There is no way to access the putput of previous prompts of the same session or any previous session. the desktop app had a repo sync option - the web version does not have one.

**Comment by HRA42** [comment]
@derickdsouza We pushed some updates in the last few weeks. If the issue still persists let us know and I will reopen the issue.
