### ISSUE TITLE
Eternal loading

### ISSUE THREAD

**Issue by ryantixier** [devgpt-labs/devgpt-releases#158]
The generator worked the first two times I used it, but now it no longer works; I get a loading bar that indefinitely runs.

<img width="920" alt="Screenshot 2023-09-25 at 3 14 12 AM" src="https://github.com/devgpt-labs/devgpt-releases/assets/123503138/3ef5b337-8899-4cab-8268-ec0a10fbf3b4">

**Comment by ash-lewis** [comment]
Hi Ryan! Please use the web version of devgpt, we've temporarily taken the desktop app offline while we get feature parity with the web version
