### ISSUE TITLE
It's still thinking...

### ISSUE THREAD

**Issue by Mike-Proven** [devgpt-labs/devgpt-releases#165]
how long before I turn it off or just end the app? It has been thinking for the past 30+ minutes or so, being literal here. I asked for a godot game engine front end with a golang server back end. I know, weird combo, but I have been in tutorial hell and thought I should give this a try.

**Comment by HRA42** [comment]
Hi @Mike-Proven 

Do you use the web version?

You can find it [here](https://code.devgpt.com)

**Comment by HRA42** [comment]
Got no feedback for 30 days. Will close for now.

@Mike-Proven if you still have problems, just let us know and I will reopen the issue.
