### ISSUE TITLE
Disappearance of organisation repos after Premium

### ISSUE THREAD

**Issue by BastinJafari** [devgpt-labs/devgpt-releases#167]
I switched to Premium and now my organisation repos are not visible anymore:, even though DevGPT has access to it.

**Comment by Marfarita** [comment]
Nie usprawiedliwia to do wyłudzania pieniedzy obiecując potężne zyski

**Comment by HRA42** [comment]
Hi @BastinJafari @Agramenti,

the Issue should be fixed. If you still have Issues, please let us know and I will reopen the issue.
