### ISSUE TITLE
Download our latest verson link leads to empty release page: https://github.com/devgpt-labs/devgpt-releases/releases

### ISSUE THREAD

**Issue by stefanrows** [devgpt-labs/devgpt-releases#168]
The "Download our latest version" link on the website: https://docs.devgpt.com/february-labs/product-guides/installation leads to an empty release repository, making it impossible for new users to download the software.

**Comment by HRA42** [comment]
Hi @stefanrows :)

You are right. Currently we don't support any old release of the desktop app.

For now we only support the [web version](https://code.devgpt.com)

Stay tuned for the future!
