### ISSUE TITLE
Nothing generating

### ISSUE THREAD

**Issue by Pigiotyreal** [devgpt-labs/devgpt-releases#174]
When I ask a question, it only follows up with "What is the purpose of this task?", and then never generators anything and just thinks.

**Comment by davenmir** [comment]
This happened a lot to me when I was still trying to use the desktop app. If you are still using the desktop version then switch to the browser version. All support for desktop has stopped for now.

**Comment by JacobRuddiman** [comment]
This is happening for the browser for me. Most of the time too

**Comment by HRA42** [comment]
Hi @Pigiotyreal :)

Thanks for reporting. The desktop app isn't supported anymore (at least for now). Please use the [web app.](https://code.devgpt.com/)

If you still have issues, please let us know and I will reopen the issue.
