### ISSUE TITLE
Premium account migration from email/pass to github changed to free tier

### ISSUE THREAD

**Issue by jaimu97** [devgpt-labs/devgpt-releases#175]
Hi, DevGPT team!

I am trying to move my account from the app's user/pass system to GitHub's OAuth with the email of my app login as one of my recovery emails in my GitHub account. However, after approving DevGPT's request to view all my emails in associated to my GitHub account, it has placed me in the free tier and shows only my primary email on my account.

**Comment by HRA42** [comment]
Hi @jaimu97 could you send us the mail you used for signing up for the desktop app and your github primary mail address? You can send it to: support@devgpt.com
