### ISSUE TITLE
@ 'tab to accept suggestion' inputs at wrong place

### ISSUE THREAD

**Issue by JacobRuddiman** [devgpt-labs/devgpt-releases#182]
When pressing tab for @ autocompletion, the remaining directory is placed at the beginning (and sometimes end??) of all prompt text:

Make a fun game _@g_ , it should be space-themed 
When pressing tab produces:
_~perfect_solitaire/game.py_Make a fun game _@g_ , it should be space-themed

**Comment by HRA42** [comment]
Hi @JacobRuddiman :)

We pushed some update over the last few weeks. The issue seems gone for me.

If you still have issues please let us know. :)
