### ISSUE TITLE
Once i login It scans repo but not a fresh scan. 

### ISSUE THREAD

**Issue by ap-coder** [devgpt-labs/devgpt-releases#189]
Also when it hangs up on a prompt and i try to refresh page it makes me login again and makes me reselect the repo. Not only is this really annoying but every time i do reselect it in console it says already scanned so its not seeing any changes i have pushed to it. 

**would it be possible to add a stop generating button or something for when it hangs. possibly also a refresh repo scan so it notices the changes pushed to it.?**

**Comment by HRA42** [comment]
Hi @ap-coder :)

We pushed some updates. Now the model retrains itself, so this shouldn't happen anymore. 

If you still have issues, please let us know!
