### ISSUE TITLE
Clicking Select model -> confirm billing -> billing confirmed [end of flow]

### ISSUE THREAD

**Issue by DoctorSquareDave** [devgpt-labs/devgpt-releases#219]
1. Click Select Model
2. I have an early bird plan already, but the only option I have is View Billing or Email Support
3. I click View Billing
4. Shows me I already have Individual plan selected
5. Can't do anything from here, except restart this flow

**Comment by tom-lewis-code** [comment]
hey @DoctorSquareDave, thank you for reporting this! I'll add some debugging to the console so we can figure out why this may be happening for your account. I'm not had any reports of this so far but I will look further into it to see if I can find a cause.

I'll update this issue with any news :)

**Comment by tom-lewis-code** [comment]
Update for this issue: I'm quite certain I've noticed and fixed this issue, I'll be pushing a PR shortly for it. I've also added a console log in this area so that users may be able to self-diagnose in the future with the help of support.

I really appreciate the bug report @DoctorSquareDave!

**Comment by HRA42** [comment]
@tom-lewis-code this should be live by now right?

**Comment by DoctorSquareDave** [comment]
Can confirm that this no longer happens, and appears to be working. Thank you

**Comment by DoctorSquareDave** [comment]
Appears to be fixed
