### ISSUE TITLE
Auto update does not work in 1.0.7

### ISSUE THREAD

**Issue by derick-dsouza** [devgpt-labs/devgpt-releases#30]
![image](https://github.com/february-labs/devgpt-releases/assets/74296942/4aa77db0-1008-4639-a5f7-9f0c8e26b654)
Have been on this screen for the last 10 mins. Gave up and manually installed v10.8.

**Comment by tom-lewis-code** [comment]
hey @derick-dsouza, thank you for reporting this! We may do an announcement in Discord: because our version on Windows is not notarised yet, it seems the auto-update isn't starting. This will be corrected next week when we have windows approval.

Sorry about this! I'm glad you fixed it :)
