### ISSUE TITLE
Upvote / Downvote / Copy / Sync buttons go over the header (zIndexing issue)

### ISSUE THREAD

**Issue by tom-lewis-code** [devgpt-labs/devgpt-releases#33]

**Comment by deeayeen** [comment]
@tom-lewis-code 

Hey, any more context on this? Still relevant?

**Comment by deeayeen** [comment]
@tom-lewis-code 

https://github.com/february-labs/devgpt-releases/pull/78

**Comment by deeayeen** [comment]
@ash-lewis shall we close this issue? (PR merged)
