### ISSUE TITLE
wrong file extensions

### ISSUE THREAD

**Issue by Vmarcelo49** [devgpt-labs/devgpt-releases#38]
i asked the ai to write some simple go code for an asteroids clone, while it did write code that worked, the extensions were all over the place, ".js", ".py" not a single one was .go
![image](https://github.com/february-labs/devgpt-releases/assets/50602525/33f88b73-f12e-4e89-b51a-3c2776d99fc7)

**Comment by plichard** [comment]
Same here, gave it a rust codebase, and it wrote fixes with javascript extensions (the code was still rust though). Using the sync button then just created new js files instead of modifying existing ones.

**Comment by tom-lewis-code** [comment]
hey @plichard and @Vmarcelo49, my main suggestion would be to make sure your tech stack matches what you're generating, although I'm sure you both probably already have this set up correctly. We don't have anything built in to the generation that would give it a preference of py or js files, so this should be entirely derived from the prompt! :) I'll keep this issue open until we see some resolution for it
