### ISSUE TITLE
Possible macOS issue during sign-up after initial app download

### ISSUE THREAD

**Issue by zessu** [devgpt-labs/devgpt-releases#40]
After downloading the app on macOS, I was trying to create an account in the sign-up process.
I entered my email but accidentally forgot to enter a password. I got a toast notification that a password was required which is expected.
I created a password and entered it in the password input box, but the loading state of the sign-up button had not been cleared making it impossible to click the button again. I had to close the app and start the whole process again

**Comment by HRA42** [comment]
This is still present in the current version.
