### ISSUE TITLE
Windows Defender problem

### ISSUE THREAD

**Issue by LBeckX** [devgpt-labs/devgpt-releases#41]
# Windows
- Windows 11
- Version	10.0.22621 Build 22621

# Defender
- Windows-Sicherheit Anwendungsversion: 1000.25873.0.9001
- Windows-Sicherheitsdienst Version: 1.0.2306.10002-0
- Antimalware-Clientversion: 4.18.23080.2006
- Modulversion: 1.1.23080.2005
- Antiviren-Version: 1.397.637.0
- Antispyware-Version: 1.397.637.0
![image](https://github.com/february-labs/devgpt-releases/assets/11272361/3d7e4152-9322-408a-9443-636b03d255d2)

**Comment by tom-lewis-code** [comment]
hey @LBeckX, thank you for reporting this! We are actively working on this issue for Windows Signing, it's been a huge project for us. It's already signed on Mac but sadly Windows takes a little longer. I'll leave this issue open until we have code signing in and this warning is removed :)
