### ISSUE TITLE
Daily limit not resetting

### ISSUE THREAD

**Issue by thorrak** [devgpt-labs/devgpt-releases#56]
I tried DevGPT for the first time ~36 hours ago, but the daily limit still shows the initial query I sent through:

<img width="189" alt="Screenshot 2023-09-11 at 10 04 46 AM" src="https://github.com/february-labs/devgpt-releases/assets/2457900/575a248c-9697-483d-bacb-3437d57d32c9">

**Comment by tom-lewis-code** [comment]
hey @thorrak, thank you for reporting! We've not seen any issues yet with this stopping users from prompting but we'll look into it. Appreciate it!
