### ISSUE TITLE
No way to change "Excluded file" list once set

### ISSUE THREAD

**Issue by thorrak** [devgpt-labs/devgpt-releases#59]
As a follow-on to #54, currently there doesn't appear to be any way to change the "excluded file" list once set, which means that there is effectively no way to change projects if the project doesn't happen to have the same structure/excluded files. 

Ideally, #54 would be implemented, but as it stands there isn't an alternative due to this issue.

**Comment by tom-lewis-code** [comment]
hey @thorrak, we have a feature incoming that will completely change how repos are handled and how a user will be able to work with multiple repos. I'll keep this issue up to date with that change. Thank you for reporting this, we did find during user testing a lot of people finding it difficult to work with multiple repos
