### ISSUE TITLE
Why is it asking me what the datatype is for this prompt? Doesn't it have access to the code?

### ISSUE THREAD

**Issue by ScottBeeson** [devgpt-labs/devgpt-releases#60]
![image](https://github.com/february-labs/devgpt-releases/assets/108358/613e4c6b-237d-441d-8dc4-9c33df75f01a)

Can someone explain?

**Comment by tom-lewis-code** [comment]
hey @ScottBeeson, sorry that this was quite a confusing question! The AI may as for clarification or more information, even if it is something it already has information on. Not all questions strictly need answering, so with some you are welcome to click Escape, which will autofill the answer of "I don't know"

We're working on making sure the question generation will stop asking questions that it already has knowledge of. Either way, thank you for your report! :)

**Comment by ash-lewis** [comment]
I have an idea of how we can improve this, we currently feed your context too late in the chain, I'll improve the questions on next release
