### ISSUE TITLE
File location tooltip falls outside of viewport when at end of prompt box

### ISSUE THREAD

**Issue by uucyy** [devgpt-labs/devgpt-releases#61]
As per title.

Assuming that this is using Electron, you could use popovers + anchors to implement these tooltips as popovers will change position to remain within the viewport while staying attached to the anchor.

Little read though of popovers with anchors https://dev.to/ubahthebuilder/how-to-use-the-new-css-anchor-feature-for-popovers-aj

**Comment by tom-lewis-code** [comment]
hey @uucyy, appreciate this suggestion! Our current implementation of the tooltip for file location could use work. I'll leave this issue open until we have something a bit smoother!
