### ISSUE TITLE
REMOVED ALL FILE DATA

### ISSUE THREAD

**Issue by saad-shamsi** [devgpt-labs/devgpt-releases#63]
the dev gpt chnged my whole 2000+ lines of code and provideed me in few lines and my 300+lines injust few lines and removed my all data when i synced it did not cmake a change in my existing code base

**Comment by HRA42** [comment]
That should be fixed with the latest version. Could you try to update to the latest version from the release page:
https://github.com/february-labs/devgpt-releases/releases
