### ISSUE TITLE
Taking over 25 Minutes to execute the very first task

### ISSUE THREAD

**Issue by OMS1996** [devgpt-labs/devgpt-releases#65]

**Comment by HRA42** [comment]
Hi @OMS1996 :)

Please check this:
1. You've manually installed version 1.1.0 from the downloads https://www.devgpt.com/download
1. You are pointing at a repo in the settings that you have on your local machine
1. You aren't trying to use a repo that has a really high file count (+100,000). Even if the file count isn't high, please try a different repo - we've had a lot of reports of some repos not functioning correctly.
1. You've restarted the app, and signed out and signed back in.
1. You don't have an extremely long context that may confuse the AI

You can find the release page here:
https://github.com/february-labs/devgpt-releases/releases

**Comment by yashkite** [comment]
I'm also facing the same problem, For the repo I have given an Android app project.

**Comment by HRA42** [comment]
@yashkite Did you check to above mentioned solutions?

**Comment by yashkite** [comment]
> @yashkite Did you check the above-mentioned solutions?
yes, it's working fine with a new project. but not with the project I'm working on, If it's not going to help me in the work that I like to do then its not worth the time

**Comment by HRA42** [comment]
@yashkite @OMS1996 

The devs will release a new version later today that will stop a bunch of these issues. We will let you know when its out.

**Comment by yashkite** [comment]
> @yashkite @OMS1996 
> 
> The devs will release a new version later today that will stop a bunch of these issues. We will let you know when its out.


Thanks for this much fast support, i really appreciate
