### ISSUE TITLE
Stripe processing error.

### ISSUE THREAD

**Issue by FentonA** [devgpt-labs/devgpt-releases#70]
I think there may be an issue with the stripe endpoint. I keep getting the following whenever i try to trigger an upgrade on my account: 
`{
  "error": {
    "message": "Unrecognized request URL (GET: /v1/payment_pages/cs_live_b1UHeLGBOobLncdnhuALJT10JSuCss2MKlfOxbGlCMA0APuBhbUa4ajB4h/confirm). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}`

In the user interface this appears as the following however: 

<img width="426" alt="Screenshot 2023-09-12 at 8 20 50 PM" src="https://github.com/february-labs/devgpt-releases/assets/46092106/a4f1de58-d5b1-498b-bd6d-bf4329a8c16b">

I've confirmed that nothing was wrong with my issuer, and the error I get back doesn't seem to reflect a transaction error. 
Any idea what could be causing this? Would this be a bug?

**Comment by FentonA** [comment]
yep, currently running 1.1.0

<img width="445" alt="Screenshot 2023-09-13 at 11 04 29 AM" src="https://github.com/february-labs/devgpt-releases/assets/46092106/90a0c5f7-7166-457c-89ea-48878258be22">

**Comment by ash-lewis** [comment]
Hi @FentonA, we seemingly have no control over this as the billing is provided by Stripe, can you confirm that this error occurred on the Stripe website? Thank you! I'll also send them this in a support email so that they can advise.

**Comment by FentonA** [comment]
hi @ash-lewis , Yes this is only happening in the stripe view/ website. 
Thanks so much
