### ISSUE TITLE
After a few lines the app just sarts spining and doesn't stop

### ISSUE THREAD

**Issue by peterturquoise** [devgpt-labs/devgpt-releases#73]
After a few lines describing the project the app just shows a spinning icon which  doesn't stop. There's then no (at least obvious) way to reload the descriptions I've already given so I have to start again (twice now).  

I've written in a separate a 3K (character) long description that answers some of the questions the app is asking, so I;d really like just to post that in one go, which would hopefully also prevent the app just ahanging idchat 

<img width="978" alt="Screenshot 2023-09-12 at 17 32 34" src="https://github.com/february-labs/devgpt-releases/assets/12343560/dc9b11cb-41f8-4c49-b1ed-22c2dd2f56ee">

**Comment by HRA42** [comment]
Hi @peterturquoise :)

Thank you for letting us know. The devs are working on a fix for some of the hanging issues, they will prob. Push a release later today. We will let you know when it's out, so you can try again.

---

In the meantime, we posted a list on Discord with things you can try to resolve this:

1. Issues:
  - Prompt was too long
  - Repo was completely empty
  - On a previous version
  - Were writing a prompt that was failing (e.g. asking a question in the prompt, providing code in a prompt to work on instead of pointing to an existing file in a repo)
  - The context was far too long
2. Suggestions:
- Rewrite your prompt to the following style (In X file, do this thing)
- Download the newest version
- Test on multiple repos instead of the same repo
- Simplify your tech stack and context

**Comment by peterturquoise** [comment]
This is a completely new project with no files, there's no repo (so the repo  _is_  empty but how do I add anything?)  the folder the project points to is also empty. I'm just getting started and giving brief descriptions of what's on the home and a couple of other screens, but no code yet.

- The prompt I entered before it failed said "Not yet" - so hopefully it's not too long
- I don't know how to tell if the context was even too long, let alone far too long...
- I;ve just downloaded it so hopefully it's the latest version


Do I have to create a repo for it ?

**Comment by MichalKurzewski** [comment]
i have the same issue. i had js react component and wanted type safety. after prompts of asking for type safety again and again the progress bar just flickers. i mean its not the rocket science i wanted here. i can do it myself its just gymnastics. glad i didnt pay for it.
-prompt was not too long. 
-repo is not empty - i pointed to the file with @
-i just installed freshest version

**Comment by peterturquoise** [comment]
I've updated to the latest version of the app but the same problem of it just hanging after entering a few short instructions is there 

<img width="1298" alt="Screenshot 2023-09-14 at 09 52 33" src="https://github.com/february-labs/devgpt-releases/assets/12343560/b392e249-aad5-42c3-9f20-9facffe2239d">

Eventually the app came back and said "I think something went wrong... please try again later or let us know in Discord."

- The initial task I gave was short
- I gave short answers to questions
- I kept the requirements simple, not auth, no scaling

DevGpt seems less useful than I though it would be for my use case which I've stripped back to scaffolding a new project. I have a few layers blockchain, api, app and I'd like to get something very simple working e2e. I reigned in my expectations and tried something pretty simple but I still have the same issue of the app hanging. It seems "ambitious" to call this a v1+ product when I can't even get past 5 questions of the initial chat phase - it seems like a 0.x early version ?

<img width="1287" alt="Screenshot 2023-09-14 at 10 07 54" src="https://github.com/february-labs/devgpt-releases/assets/12343560/4e016b6a-a3bc-4848-bc30-8ca639261153">


Also, DevGPT doesn't keep conversation context unlike most chat models, so I have to start everything again if something fails - it would be a huge improvement if I at least didn't have to start from the beginning every time
