### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by francescotinti** [devgpt-labs/devgpt-releases#83]
Hello, the app stopped working by two days.
The first 2 prompts perfectly worked, then it stopped producing code.
As I create a new task and answer to the 3-4 questions, DevGPT seems generating code, but it doesn't work.
May you help me ? Thank you.

**Comment by ash-lewis** [comment]
Hi @francescotinti , can you please try this again on version 1.1.1? If that doesn't work can you please make a new issue with the following bits of info:

prompt used
error message
version number
OS

Thank you!

**Comment by francescotinti** [comment]
Let's write some code!
I

Create a new file named test_bug.py into the src folder. Use Flask to
create a minimal application with that routing / return "<p>Hello
world!</p>"

What is the exact functionality of the test_bug.py file?
I

quickly prototying a Flask app

Does the Flask application need to interact with the Google Ads API?
I

yes

Are there any specific Flask configurations or extensions that need to be
included in the Flask application?
I

reading a YAML config file with Google Ads token

Do I need to integrate any Javascript code into the Flask application?
I

Yes

I think something went wrong... please try again later or let us know in
Discord.

Il giorno gio 14 set 2023 alle ore 12:20 Ash Lewis ***@***.***>
ha scritto:

**Comment by HRA42** [comment]
Hi @francescotinti 

Could you please let us know:

- Did you receive an Error message?
- Which Operating System do you use?

**Comment by francescotinti** [comment]
Don't receive error.
DevGPT version is 1.1.1
Operating system is Mac OS X Ventura.

Please note that if I use DevGPT on a Debian Linux environment, everything
works fine.

Il giorno ven 15 set 2023 alle ore 00:28 Henry Rausch <
***@***.***> ha scritto:
