### ISSUE TITLE
File Lookup Not Working

### ISSUE THREAD

**Issue by stingrayfunk** [devgpt-labs/devgpt-releases#85]
Version: 1.1.0

File lookup is not working, despite that file existing in the target repo.

<img width="1370" alt="Screenshot 2023-09-13 at 3 45 42 pm" src="https://github.com/february-labs/devgpt-releases/assets/1764083/07c2997e-6020-4aba-b852-ba29194a5061">

**Comment by martinstanojevic** [comment]
Same here. 

I have a (turbo) monorepo and files in `packages` folder are being completely ignored. I cannot select the files even if I select the folder containing the file I want to select as a target folder.

**Comment by HRA42** [comment]
@stingrayfunk @martinstanojevic 

Could you download the latest release (v1.1.1) and try again?

If it's not working, please let us know! :)

**Comment by martinstanojevic** [comment]
@HRA42 thanks for the quick response. It's still not working. 

I cannot access any file in the `./packages/` folder.

**Comment by HRA42** [comment]
@martinstanojevic
Could you post your prompt?

**Comment by martinstanojevic** [comment]
@HRA42 sure! 

Here's a screenshot of me trying to select `Calculator.service.ts`:
![devgpt](https://github.com/february-labs/devgpt-releases/assets/5338220/4bb83a4f-8df2-40fc-8568-277de8853e8f)

DevGPT is suggesting only files located in `apps` folder:
