### ISSUE TITLE
[Bug]Still not Working 

### ISSUE THREAD

**Issue by shnkt** [devgpt-labs/devgpt-releases#99]
Its still not working getting following error :
I think something went wrong... please try again later or let us know in Discord.

This is insane does it even work as expected disappointed

**Comment by ash-lewis** [comment]
Hey shnkt, we could use some more details to debug this, can you please let us know your version number, your OS and your prompt? Thanks

**Comment by shnkt** [comment]
Yes I am using windows 11 and I am just using create code for addition of 2 numbers and it asks for input and then says something went wrong

**Comment by shnkt** [comment]
how long would take to fix things up as I have taken the paid version of the app.

**Comment by christophmayrhofer** [comment]
Same problem.

OS: Windows 11 Home 22H2
Version: 1.1.1

prompt: add a script to verify an email address

then it asks some questions 

then it loads for a few minutes. 

then it says: I think something went wrong... please try again later or let us know in Discord.

**Comment by gytisptasinskas** [comment]
Same for me

OS: MACOS Ventura 13.3.1 (a) 
Version: 1.1.1

Loads after few minutes getting response I think something went wrong... please try again later or let us know in Discord.

**Comment by paulgovers** [comment]
Same for me

OS: Windows 11 Business
Version: 1.1.1 Premium version

Paid but not working :-(
